{"uuid": "7568f73e-8497-4106-8de5-a84f2d1e37fd", "children": ["a671b12d-0656-4dc5-a653-c97a69031f6e", "c970326d-32f9-4dc1-9639-7c0689dc0653", "f8a97d1e-5fd8-4bb0-a947-551a6708d24e", "7eaf9422-2cfc-4471-a241-a9eb2277fcad", "9d34949d-9935-4df7-935c-189da9c0ce3e"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: 'MtxLogin' object has no attribute 'url'\n", "trace": "  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\python.py\", line 745, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\python.py\", line 674, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\company\\auto\\20200606\\lesson12\\apiFrame\\script\\test_login.py\", line 11, in setup_class\n    self.login_obj = MtxLogin()\n  File \"D:\\company\\auto\\20200606\\lesson12\\apiFrame\\api\\loginApi.py\", line 17, in __init__\n    log.info(f'登录的url地址是{self.url}')\n"}, "start": 1599197819818, "stop": 1599197819818}], "start": 1599197819818, "stop": 1599197819898}