{"name": "登录异常，测试数据是:{'accounts': 'yaoyao', 'pwd': '123456', 'exp': '密码错误'}", "status": "broken", "statusDetails": {"message": "AttributeError: 'MtxLogin' object has no attribute 'url'", "trace": "self = <class 'script.test_login.TestLogin'>\n\n    def setup_class(self):\n        self.session = requests.Session()\n        # 实例化接口对象\n>       self.login_obj = MtxLogin()\n\nscript\\test_login.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.loginApi.MtxLogin object at 0x000001FAF66EF048>\n\n    def __init__(self):\n>       log.info(f'登录的url地址是{self.url}')\nE       AttributeError: 'MtxLogin' object has no attribute 'url'\n\napi\\loginApi.py:17: AttributeError"}, "description": "\n        对登录接口进行异常登录的测试\n        :param args: 参数化的数据\n        :return:\n        ", "parameters": [{"name": "args", "value": "{'accounts': 'yaoyao', 'pwd': '123456', 'exp': '密码错误'}"}], "start": 1599197819893, "stop": 1599197819893, "uuid": "9d34949d-9935-4df7-935c-189da9c0ce3e", "historyId": "9b1c39a42a17c4eb61b2e9ff0cabd0ab", "testCaseId": "acfd50c72596b11b4392c40d7652bccf", "fullName": "script.test_login.TestLogin#test_login_error", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-60EEKMHU"}, {"name": "thread", "value": "17868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}